name: Build and upload to latest release

on:
  release:
    types: [published]

jobs:
  build-and-upload:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore SVModAPI.sln

      - name: Build project
        run: dotnet build SVModAPI.sln --configuration Release --no-restore

      - name: Publish for Linux
        run: dotnet publish SVModAPI/SVModAPI.csproj --configuration Release --framework net9.0 --runtime linux-x64 --self-contained true --output ./publish/linux-x64

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: addon
          retention-days: 1
          path: linux-x64.zip

      - name: Upload ZIP to release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: linux-x64.zip
          update_latest_release: true